# fly.toml app configuration file generated for valkey
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
app = 'valkey-ayvu'
primary_region = 'iad'

[build]
image = "ghcr.io/fermuch/valkey-fly:main"

[http_service]
internal_port = 6379
force_https = true
auto_stop_machines = "off"
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory_mb = 1024

[mounts]
  source = "valkey_data"
  destination = "/data"
  snapshot_retention = 14
  auto_extend_size_threshold = 80
  auto_extend_size_increment = "5GB"
  auto_extend_size_limit = "20GB"

[env]
  VALKEY_DATA_DIR = "/data"
  SWAP_SIZE = "2G"
  # secret: VALKEY_PASSWORD

